---

- hosts: all
  become: true
  pre_tasks:
   
    - name: install Updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers 
  become: true
  tasks:

    - name: install apache and php for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package for Ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
