---

- hosts: all
  become: true
  pre_tasks:
   
    - name: install Updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for Ubuntu
      tags: apache,apache2,ubuntu 
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache,apache2,ubuntu
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: start apache onf Ubuntu automatically
      tags: apache,apache2,ubuntu
      service: 
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"       

    - name: change Timeout setting for apache2.conf
      tags: apache,apache2,ubuntu
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^Timeout'
        line: Timeout 500
      when: ansible_distribution == "Ubuntu" 
      register: apache2_conf_changed

    - name: restart apache2 (Ubuntu)
      tags: apache,apache2,ubuntu
      service:
        name: apache2
        state: restarted
      when: apache2_conf_changed.changed
    

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package for Ubuntu
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
