- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: change Timeout setting for apache2.conf
  tags: apache,apache2,ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^Timeout'
    line: Timeout 500
  when: ansible_distribution == "Ubuntu" 
  register: apache2_conf_changed
 
- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
